In [8]:
##### Lab-07-01 : Exercise 7-1 수행
##
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [9]:
arr1 + arr2

array([11, 22, 33, 44])

In [10]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [11]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [12]:
arr1 / arr2

array([10., 10., 10., 10.])

In [13]:
arr2 *2

array([2, 4, 6, 8])

In [14]:
arr2 **2

array([ 1,  4,  9, 16], dtype=int32)

In [15]:
1 / arr2

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [16]:
arr1 > 20

array([False, False,  True,  True])

In [37]:
##### Lab-07-02 : 행렬연산
##
import numpy as np

# 배열 생성
A = np.random.randint(0,10, size = (3,2))
B = np.random.randint(0,10, size = (4,2))

# 전치행렬 연산
B = B.transpose()

# 행렬곱 연산
C = A.dot(B)

# 출력
print("합: %d, 평균: %1.3f, 최대값: %d, 최솟값: %d, 분산: %1.3f \n" % (C.sum(), C.mean(), C.max(), C.min(), C.var()))
print('누적곱 : ', C.cumprod())


합: 362, 평균: 30.167, 최대값: 60, 최솟값: 14, 분산: 171.639 

누적곱 :  [         26        1196       38272      612352    20819968  1249198080
 -1571684352 -1368915968 -1984954368   -69206016  2080374784 -1073741824]


In [36]:
##### Lab-07-02 : 배열생성연습
##
import numpy as np

# 2x3 형상을 갖는 2차원 배열
A = np.array([[1,2,3],[4,5,6]])

# 2x2x3 형상을 갖는 3차원 배열
B = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# 2x3x2 형상을 갖는 3차원 배열
C = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

# 3x2x2 형상을 갖는 3차원 배열
D = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

# 3x4x2x2 형상을 갖는 4차원 배열
E = np.array([[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[15,16]]],
              [[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[15,16]]],
              [[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[15,16]]]])

# 배열의 차원 확인
print("A =", A.shape)
print("B =", B.shape)
print("C =", C.shape)
print("D =", D.shape)
print("E =", E.shape)   
print()

# slicing 한 배열 출력
print("slicedA =", A[1][1:])
print("slicedB =", B[1,0,:2])
print("slicedC =", C[1][0:,1:])
print("slicedD =", D[2:][0:,:1])
print("slicedE =", E[1,2:,1:])

A = (2, 3)
B = (2, 2, 3)
C = (2, 3, 2)
D = (3, 2, 2)
E = (3, 4, 2, 2)

slicedA = [5 6]
slicedB = [7 8]
slicedC = [[ 8]
 [10]
 [12]]
slicedD = [[[ 9 10]]]
slicedE = [[[11 12]]

 [[15 16]]]
